### ISSUE TITLE
What is the font you're using?

### ISSUE THREAD

**Issue by r004** [daGrevis/Dotfiles#1]
Hello;
Very nice setup you got going there man. I ripped most of mine from you without saying Thank You! (sorry-thanks)
But the thing that I couldn't figure out was the fonts you are using.
left-side primary section
![left side](https://camo.githubusercontent.com/4ded6e1d5e4a9d2787be1de7a6cdf22042f55e3c/68747470733a2f2f7261772e6769746875622e636f6d2f64614772657669732f446f7466696c65732f6d61737465722f53637265656e73686f74732f6769742e706e67)
or in your browser

![browser](http://a.pomf.se/jxrylu.jpg)
could you help me out here!
Cheers

**Comment by daGrevis** [comment]
Ah, I'm so sorry I didn't respond — I missed the notification and didn't see this issue until now!

For that moment in time I used:
- “Meslo LG M DZ 9“ in terminal,
- “Inconsolata-g 9“ in Vim,
- “Helvetica Neue“ in browser (Twitter is using it, I just happen to have it installed),
- “San Francisco Display“ for native windows etc.;

I'm glad you liked it. :sunglasses:
